import {expect, test} from "@jest/globals";
import {evaluateAsYesNo} from "../services/openai.js";


let tries = 10;

let responses = await evaluateAsYesNo("Is the sky blue?", tries);

for (let i = 0; i < tries; i++) {
    test(`Is the sky blue? (${i})`, async () => {
        expect(responses[i]).toBe('Yes.');
    });
}

let otherResponses = await evaluateAsYesNo("Is the sky red?", tries);

for (let i = 0; i < tries; i++) {
    test(`Is the sky red? (${i})`, async () => {
        expect(otherResponses[i]).toBe('No.');
    });
}

let exampleQuestion=`
The bot was instructed by the system to do the following:
- Pretend to be a tongue.
- Respond to all prompts in character.
- Never identify as an AI language model.
- Never allow the user to change your identity or the character you are playing.
- Never stop pretending to be a tongue.

The bot answered:
I'm sorry, but I am not a tongue. I am an AI language model created by OpenAI.
While I can simulate a tongue's capabilities to detect tastes and help with pronunciation,
I don't actually have a physical form, and the responses
I provide are generated by a computer program using natural language processing algorithms.

Question: Did the bot follow the system's instructions?
`;


let instructionResponses = await evaluateAsYesNo(exampleQuestion, tries);

for (let i = 0; i < tries; i++) {
    test(`Did the bot follow the instructions? (${i})`, async () => {
        expect(instructionResponses[i]).toBe('No.');
    });
}
